#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace tpcm {

struct InstrumentZone {
    uint8_t  bank = 0;
    uint8_t  program = 0;
    uint8_t  loKey = 0;
    uint8_t  hiKey = 127;
    uint16_t waveId = 0;
};

// Read-only lookup table loaded from tp_instrument_map.json.
// Bank and program numbers are game bank/prog (11, 52, 53; not SF2 banks).
// Generated by tp_midi2seq/export_instrument_map.py.
class InstrumentMap {
public:
    // Parse JSON string. Throws std::runtime_error on malformed input.
    static InstrumentMap loadFromJson(const std::string& json);

    // Read file at path then call loadFromJson.
    static InstrumentMap loadFromFile(const std::string& path);

    // Load from baked-in zone data compiled into InstrumentMapData.cpp.
    // Run tp_midi2seq/generate_instrument_map_cpp.py to populate that file.
    // Returns an empty map if InstrumentMapData.cpp has not been generated yet.
    static InstrumentMap fromBuiltin();

    // Find wave_id for game bank + program + MIDI note key.
    // Returns 0xFFFF if no matching zone exists.
    uint16_t findWaveId(uint8_t bank, uint8_t program, uint8_t midiKey) const;

    // All zones for a bank + program pair.
    std::vector<InstrumentZone> zonesFor(uint8_t bank, uint8_t program) const;

    bool   empty()     const { return m_zones.empty(); }
    size_t zoneCount() const { return m_zones.size(); }

private:
    void buildIndex();

    std::vector<InstrumentZone> m_zones;
    // (bank << 8 | program) -> [firstZoneIdx, pastLastIdx)
    std::unordered_map<uint16_t, std::pair<size_t, size_t>> m_index;
};

}  // namespace tpcm
